"""
Diagnostic-assessment sampling and generation.

Sampling is deterministic, not random-weighted: prerequisite roots (concepts
nobody else's prerequisite edge points at -- i.e. concepts with no
prerequisites of their own) sort first, by importance, because a diagnostic
should establish the foundation before probing anything built on it. This
mirrors the rest of the curriculum module's "deterministic over stochastic
where either would do" convention (graph.py, normalization.py).

Diagnostic generation produces one single-concept MCQ per sampled concept via
one bounded LLM call (same "one call over the bounded set" shape as
curriculum/edges.py's prerequisite proposal), not one call per concept --
MULTI_SELECT/SHORT_TEXT/NUMERIC questions are supported by the grading and
model layer but are not auto-generated by the diagnostic; a course owner or
a future authoring flow can call MasteryService.create_question directly for
those types.
"""
import json
from dataclasses import dataclass
from typing import List, Optional, Set
from uuid import UUID

from app.modules.curriculum.models import Concept, ConceptPrerequisite
from app.services.generation.gateway import GenerationGateway

MIN_DIAGNOSTIC_QUESTIONS = 8
MAX_DIAGNOSTIC_QUESTIONS = 20
_SAMPLE_RATIO = 0.6  # unvalidated default: roughly this fraction of the graph


class DiagnosticParseError(Exception):
    """Raised when the diagnostic-generation response cannot be parsed at all."""


@dataclass(frozen=True)
class DiagnosticQuestionDraft:
    concept_id: UUID
    prompt: str
    options: List[str]
    correct_answer: str
    difficulty: float


def _root_concept_ids(concepts: List[Concept], edges: List[ConceptPrerequisite]) -> Set[UUID]:
    """Concepts that are never any edge's dependent -- i.e. have no
    prerequisites of their own."""
    non_roots = {edge.dependent_concept_id for edge in edges}
    return {c.id for c in concepts if c.id not in non_roots}


def diagnostic_size(num_concepts: int, max_questions: Optional[int] = None) -> int:
    if num_concepts == 0:
        return 0
    size = round(num_concepts * _SAMPLE_RATIO)
    size = max(MIN_DIAGNOSTIC_QUESTIONS, min(MAX_DIAGNOSTIC_QUESTIONS, size))
    size = min(size, num_concepts)
    if max_questions is not None:
        size = min(size, max_questions)
    return size


def sample_concepts_for_diagnostic(
    concepts: List[Concept],
    edges: List[ConceptPrerequisite],
    max_questions: Optional[int] = None,
) -> List[Concept]:
    """Roots first (by importance desc), then the rest (by importance desc),
    truncated to diagnostic_size()."""
    roots = _root_concept_ids(concepts, edges)
    ordered = sorted(
        concepts, key=lambda c: (c.id not in roots, -c.importance, c.name)
    )
    size = diagnostic_size(len(concepts), max_questions)
    return ordered[:size]


def _strip_code_fence(text: str) -> str:
    text = text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[1] if "\n" in text else ""
        if text.endswith("```"):
            text = text[: -3]
    return text.strip()


def generate_diagnostic_questions(
    concepts: List[Concept], generation: GenerationGateway
) -> List[DiagnosticQuestionDraft]:
    """One bounded LLM call over the sampled concept set. Malformed
    individual entries are skipped (non-fatal); an unparseable whole
    response raises DiagnosticParseError."""
    if not concepts:
        return []

    concept_lines = "\n".join(f"- {c.name}: {c.definition}" for c in concepts)
    prompt = (
        "Write one multiple-choice diagnostic question per concept below, "
        "testing whether a learner already understands it before instruction.\n\n"
        f"Concepts:\n{concept_lines}\n\n"
        'Return ONLY JSON: {"questions": [{"concept_name": str, "prompt": str, '
        '"options": [str, str, str, str], "correct_answer": str (must equal one '
        'of "options" exactly), "difficulty": float between 0 and 1}]}'
    )
    raw = generation.generate(prompt, temperature=0.2)
    try:
        parsed = json.loads(_strip_code_fence(raw))
        items = parsed["questions"]
        if not isinstance(items, list):
            raise ValueError("questions must be a list")
    except (json.JSONDecodeError, KeyError, ValueError) as exc:
        raise DiagnosticParseError(f"Could not parse diagnostic response: {raw[:200]!r}") from exc

    by_name = {c.name.strip().lower(): c for c in concepts}
    drafts: List[DiagnosticQuestionDraft] = []
    for item in items:
        try:
            concept = by_name.get(str(item["concept_name"]).strip().lower())
            options = item["options"]
            correct_answer = item["correct_answer"]
            if (
                concept is None
                or not isinstance(options, list)
                or correct_answer not in options
            ):
                continue
            difficulty = float(item.get("difficulty", 0.5))
            difficulty = max(0.0, min(1.0, difficulty))
            drafts.append(
                DiagnosticQuestionDraft(
                    concept_id=concept.id,
                    prompt=str(item["prompt"]),
                    options=[str(o) for o in options],
                    correct_answer=str(correct_answer),
                    difficulty=difficulty,
                )
            )
        except (KeyError, TypeError, ValueError):
            continue
    return drafts
